version: '3'

services:
  db_async:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: async_task
    ports:
      - 5433:5433 

  db:
    image: postgres
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: request_history
    volumes:
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
    ports:
      - 5432:5432 

  worker:
    build: ./worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=******
      - SENDGRID_SEND_FROM_EMAIL=******
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db_async:5433/async_task
    volumes:
      - ./worker/worker.py:/app/worker.py

  redis:
    image: redis
    ports:
      - "6379:6379"
      
  census_report:
    build: ./census_report
    container_name: "census_report"
    ports:
      - "5050:5050"
    depends_on:
      - db


  job_viewer:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - redis

